import setuptools


major = "4"
minor = "0"
patch = "0"
tag = "a1"
version = ".".join((major, minor, patch)) + tag

with open("./src/avmath/version.py", "w", encoding="utf8") as v:
    v.write("# Generated by setup.py\n\n")
    v.write(f'version = "{version}"')


with open("README.md", "r", encoding="utf8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="avmath",
    version=version,
    author="Camillo Ballandt",
    author_email="ballandt@pm.me",
    description="Module for symbolic math",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://ballandt.github.io/p/avmath",
    project_urls={
        "Bug Tracker": "https://github.com/ballandt/avmath/issues",
        "Documentation": "https://ballandt.github.io/p/avmath/docs/4.0"
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Licence :: OSI Approved :: MIT License",
        "Operating System :: OS Independent"
    ],
    package_dir={"": "src"},
    packages=setuptools.find_packages(where="src"),
    python_requires=">=3.6",
)